const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const todayKey=()=>new Date().toISOString().slice(0,10);
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const fmtDate=d=>new Date(d+'T00:00:00').toLocaleDateString(undefined,{day:'2-digit',month:'short'});
const STORE='gymforge_v1';
const workoutPlan=[
 {name:'Push A',focus:'Chest + Shoulder + Triceps',ex:[['Bench Press',4,'6–8'],['Incline DB Press',3,'8–10'],['Shoulder Press',3,'8–10'],['Lateral Raise',3,'12–15'],['Triceps Pushdown',3,'10–12']]},
 {name:'Pull A',focus:'Back + Biceps',ex:[['Lat Pulldown / Pull-up',4,'8–10'],['Barbell Row',3,'8–10'],['Seated Cable Row',3,'10–12'],['Face Pull',3,'12–15'],['Barbell Curl',3,'10–12'],['Hammer Curl',2,'10–12']]},
 {name:'Legs A',focus:'Quads dominant',ex:[['Squat',4,'6–8'],['Leg Press',3,'10–12'],['Leg Extension',3,'12–15'],['Leg Curl',3,'10–12'],['Calf Raise',4,'12–15'],['Abs',3,'12–15']]},
 {name:'Push B',focus:'Chest + Shoulder + Triceps',ex:[['Incline Bench',4,'6–10'],['Machine / DB Chest Press',3,'8–12'],['Cable Fly',3,'12–15'],['DB Shoulder Press',3,'8–10'],['Lateral Raise',3,'15–20'],['Overhead Triceps Extension',3,'10–12']]},
 {name:'Pull B',focus:'Back + Biceps',ex:[['Pull-up / Lat Pulldown',3,'8–12'],['Chest-supported Row',4,'8–12'],['One-arm DB Row',3,'10–12'],['Rear Delt Fly',3,'12–15'],['Preacher Curl',3,'10–12'],['Hammer Curl',3,'10–12']]},
 {name:'Legs B',focus:'Hamstrings + Glutes',ex:[['Romanian Deadlift',4,'6–10'],['Bulgarian Split Squat',3,'8–10'],['Leg Curl',3,'10–15'],['Leg Press',3,'10–12'],['Calf Raise',4,'12–20'],['Plank',3,'45–60s']]},
];
const dietPlan=[
 ['Breakfast','3 eggs (2 whole + 1 white), 3–4 roti or oats, 250 ml milk'],
 ['Mid-morning','1 fruit + 30–40 g roasted chana/peanuts'],
 ['Lunch','2–2.5 cups rice + dal + vegetables + 120–150 g chicken/fish + salad'],
 ['Pre-workout','1 banana + 2 bread or boiled potato; tea/coffee optional'],
 ['Post-workout','250–300 ml milk + 2 eggs, or curd + banana'],
 ['Dinner','Rice/3–4 roti + 120–150 g fish/chicken + dal + vegetables'],
 ['Before bed','1 glass milk or 100–150 g curd'],
];
const defaults={
 profile:{name:'Vishwayan',weight:57,height:174,target:60,calories:2450,protein:105,carbs:330,fat:65,startWeight:57},
 recovery:{sleep:8,water:2.2,waterTarget:3},weights:[{id:uid(),date:todayKey(),value:57}],measurements:[],prs:[],notes:[],clients:[],plans:[],workouts:[],meals:{},setLogs:{},settings:{},
};
let state=load(); let selectedWorkout=(new Date().getDay()+5)%7; if(selectedWorkout>5)selectedWorkout=0;
let modalHandler=null, deferredPrompt=null, sessionSeconds=0,sessionInt=null,restSeconds=90,restDefault=90,restInt=null;
function clone(o){return JSON.parse(JSON.stringify(o))}
function load(){try{return {...clone(defaults),...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return clone(defaults)}}
function save(){localStorage.setItem(STORE,JSON.stringify(state)); renderAll(); cloudSaveDebounced();}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function dayMeals(){return state.meals[todayKey()]||[]}
function macroTotals(){return dayMeals().reduce((a,m)=>({cal:a.cal+(+m.cal||0),protein:a.protein+(+m.protein||0),carbs:a.carbs+(+m.carbs||0),fat:a.fat+(+m.fat||0)}),{cal:0,protein:0,carbs:0,fat:0})}
function weekWorkouts(){const now=new Date(), start=new Date(now);start.setDate(now.getDate()-((now.getDay()+6)%7));start.setHours(0,0,0,0);return state.workouts.filter(w=>new Date(w.date)>=start).length}
function streak(){const days=[...new Set(state.workouts.map(w=>w.date))].sort().reverse();let s=0,d=new Date();for(let i=0;i<30;i++){const k=d.toISOString().slice(0,10);if(days.includes(k))s++;else if(i>0)break;d.setDate(d.getDate()-1)}return s}
function latestWeight(){return state.weights.length?state.weights[state.weights.length-1].value:state.profile.weight}
function progressPct(){const start=state.profile.startWeight||57, target=state.profile.target, cur=latestWeight();return clamp(((cur-start)/(target-start))*100,0,100)}
function setBar(id,val,max){const e=$(id);if(e)e.style.width=clamp(val/max*100,0,100)+'%'}
function navTo(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+v).classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#pageTitle').textContent=({dashboard:'Dashboard',workout:'Workout',nutrition:'Nutrition',progress:'Progress',notes:'Notes',trainer:'Trainer Mode',settings:'Settings'})[v];$('#sidebar').classList.remove('open');if(v==='progress')setTimeout(renderCharts,30)}
function renderAll(){renderHeader();renderDashboard();renderWorkout();renderNutrition();renderProgress();renderNotes();renderTrainer();renderSettings();}
function renderHeader(){const p=state.profile,w=latestWeight(),pct=progressPct();$('#todayLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'});$('#sidebarWeight').textContent=w.toFixed(1)+' kg';$('#sidebarTarget').textContent=p.target+' kg';$('#sidebarGoalProgress').style.width=pct+'%';$('#heroWeight').textContent=w.toFixed(1);$('#heroPercent').textContent=Math.round(pct)+'%';$('#heroRing').style.background=`conic-gradient(var(--accent) ${pct*3.6}deg,#222 0deg)`;$('#profileQuickBtn').textContent=p.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();}
function renderDashboard(){const t=macroTotals(),p=state.profile, ww=weekWorkouts();$('#dashCalories').textContent=Math.round(t.cal);$('#dashCalTarget').textContent=p.calories;$('#dashProtein').textContent=Math.round(t.protein)+'g';$('#dashProteinTarget').textContent=p.protein+'g';$('#dashWorkouts').textContent=ww;$('#dashWeightChange').textContent=(latestWeight()-(state.weights[0]?.value||p.startWeight)).toFixed(1)+' kg';setBar('#calBar',t.cal,p.calories);setBar('#proteinBar',t.protein,p.protein);setBar('#workoutBar',ww,6);$('#sleepDisplay').textContent=state.recovery.sleep+'h';$('#waterDisplay').textContent=state.recovery.water+' / '+state.recovery.waterTarget+'L';$('#streakDisplay').textContent=streak()+' days';let score=Math.round(clamp((state.recovery.sleep/8)*45+(state.recovery.water/state.recovery.waterTarget)*35+(ww/6)*20,0,100));$('#readinessScore').textContent=score;const wd=workoutPlan[selectedWorkout];$('#todayWorkoutTitle').textContent=wd.name+' · '+wd.focus;$('#todayWorkoutPreview').innerHTML=wd.ex.slice(0,5).map(x=>`<div class="preview-row"><b>${x[0]}</b><span>${x[1]} × ${x[2]}</span></div>`).join('');drawChart($('#weightMiniChart'),state.weights.slice(-8));}
function workoutKey(di,ei){return todayKey()+'_'+di+'_'+ei}
function renderWorkout(){const picker=$('#workoutDayPicker');picker.innerHTML=workoutPlan.map((w,i)=>`<button class="${i===selectedWorkout?'active':''}" data-wd="${i}">${w.name}</button>`).join('');const day=workoutPlan[selectedWorkout];$('#workoutDayHeading').textContent=day.name+' — '+day.focus;$('#exerciseList').innerHTML=day.ex.map((e,ei)=>{const key=workoutKey(selectedWorkout,ei),logs=state.setLogs[key]||Array.from({length:e[1]},()=>({kg:'',reps:'',done:false}));return `<div class="exercise"><div class="exercise-head"><div><h4>${e[0]}</h4><div class="meta">${e[1]} sets · ${e[2]} reps</div></div></div>${logs.map((s,si)=>`<div class="set-grid"><b>${si+1}</b><input data-set-field="kg" data-ei="${ei}" data-si="${si}" type="number" step="0.5" placeholder="kg" value="${s.kg||''}"><input data-set-field="reps" data-ei="${ei}" data-si="${si}" type="number" placeholder="reps" value="${s.reps||''}"><button class="done-set ${s.done?'done':''}" data-set-done="1" data-ei="${ei}" data-si="${si}">✓</button></div>`).join('')}</div>`}).join('')}
function renderNutrition(){const t=macroTotals(),p=state.profile;[['#nutCal',t.cal],['#nutProtein',t.protein],['#nutCarbs',t.carbs],['#nutFat',t.fat]].forEach(([id,v])=>$(id).textContent=Math.round(v));$('#nutCal').nextElementSibling.textContent=` / ${p.calories} kcal`;$('#nutProtein').nextElementSibling.textContent=` / ${p.protein} g`;$('#nutCarbs').nextElementSibling.textContent=` / ${p.carbs} g`;$('#nutFat').nextElementSibling.textContent=` / ${p.fat} g`;setBar('#nutCalBar',t.cal,p.calories);setBar('#nutProteinBar',t.protein,p.protein);setBar('#nutCarbsBar',t.carbs,p.carbs);setBar('#nutFatBar',t.fat,p.fat);const arr=dayMeals();$('#mealLog').innerHTML=arr.length?arr.map(m=>`<div class="meal-row"><div><b>${m.name}</b><div class="macro">${m.protein}g P · ${m.carbs}g C · ${m.fat}g F</div></div><b>${m.cal} kcal</b><button class="delete-btn" data-del-meal="${m.id}">✕</button></div>`).join(''):'<p class="muted">No food logged yet.</p>';$('#dietPlan').innerHTML=dietPlan.map(x=>`<div class="meal-plan-item"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}
function renderProgress(){const m=state.measurements[state.measurements.length-1]||{};const fields=[['Chest',m.chest],['Waist',m.waist],['Arms',m.arms],['Thigh',m.thigh]];$('#measurementGrid').innerHTML=fields.map(x=>`<div class="measure-item"><span>${x[0]}</span><strong>${x[1]||'—'}${x[1]?' cm':''}</strong></div>`).join('');$('#prList').innerHTML=state.prs.length?[...state.prs].reverse().map(p=>`<div class="list-row"><div><b>${p.exercise}</b><div class="sub">${fmtDate(p.date)} · ${p.reps||1} rep${p.reps==1?'':'s'}</div></div><b>${p.weight} kg</b></div>`).join(''):'<p class="muted">No PRs logged yet.</p>';$('#weightHistory').innerHTML=state.weights.length?[...state.weights].reverse().map(w=>`<div class="list-row"><div><b>${w.value.toFixed(1)} kg</b><div class="sub">${fmtDate(w.date)}</div></div><button class="delete-btn" data-del-weight="${w.id}">✕</button></div>`).join(''):'<p class="muted">No weigh-ins.</p>';renderCharts()}
function renderCharts(){drawChart($('#weightChart'),state.weights)}
function drawChart(canvas,points){if(!canvas)return;const ctx=canvas.getContext('2d'),dpr=devicePixelRatio||1,w=canvas.clientWidth||500,h=parseInt(canvas.getAttribute('height'))||200;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#273242';ctx.lineWidth=1;for(let i=1;i<5;i++){let y=i*h/5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}if(points.length<1)return;const vals=points.map(x=>+x.value),min=Math.min(...vals)-.5,max=Math.max(...vals)+.5, pad=14;const coords=points.map((p,i)=>({x:pad+(w-pad*2)*(points.length===1?.5:i/(points.length-1)),y:pad+(h-pad*2)*(1-(p.value-min)/(max-min||1))}));ctx.strokeStyle='#b7ff3c';ctx.lineWidth=3;ctx.beginPath();coords.forEach((c,i)=>i?ctx.lineTo(c.x,c.y):ctx.moveTo(c.x,c.y));ctx.stroke();ctx.fillStyle='#b7ff3c';coords.forEach(c=>{ctx.beginPath();ctx.arc(c.x,c.y,4,0,Math.PI*2);ctx.fill()})}
function renderNotes(){$('#notesGrid').innerHTML=state.notes.length?[...state.notes].reverse().map(n=>`<div class="note"><span class="mini-label">${n.tag||'NOTE'}</span><h4>${esc(n.title)}</h4><p>${esc(n.body)}</p><div class="note-footer"><span>${fmtDate(n.date)}</span><button class="delete-btn" data-del-note="${n.id}">Delete</button></div></div>`).join(''):'<div class="card"><p class="muted">No notes yet. Save form cues, pain flags, motivation, or coach observations.</p></div>'}
function renderTrainer(){const c=state.clients;$('#clientCount').textContent=c.length;$('#checkinsDue').textContent=c.filter(x=>x.checkin==='Due').length;$('#plansActive').textContent=state.plans.length;$('#clientList').innerHTML=c.length?c.map(x=>`<div class="client-row"><div class="client-avatar">${x.name.split(/\s+/).map(y=>y[0]).slice(0,2).join('').toUpperCase()}</div><div><b>${esc(x.name)}</b><div class="sub">${esc(x.goal)} · ${x.weight} kg</div></div><span class="pill">${x.checkin||'Active'}</span></div>`).join(''):'<p class="muted">No clients yet. Trainer Mode also works as your future coaching dashboard.</p>';$('#planClient').innerHTML=c.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')||'<option value="">Add a client first</option>'}
function renderSettings(){const p=state.profile;$('#profileName').value=p.name;$('#profileWeight').value=latestWeight();$('#profileHeight').value=p.height;$('#profileTarget').value=p.target;$('#profileCalories').value=p.calories;$('#profileProtein').value=p.protein;$('#profileCarbs').value=p.carbs;$('#profileFat').value=p.fat}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function openModal(title,html,handler){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=`<div class="modal-fields">${html}</div>`;modalHandler=handler;$('#modal').showModal()}
function weightModal(){openModal('Log body weight',`<label>Weight (kg)<input id="mWeight" type="number" step="0.1" value="${latestWeight()}" required></label><label>Date<input id="mDate" type="date" value="${todayKey()}" required></label>`,()=>{const v=+$('#mWeight').value;if(!v)return;state.weights.push({id:uid(),date:$('#mDate').value,value:v});state.weights.sort((a,b)=>a.date.localeCompare(b.date));state.profile.weight=v;save();toast('Weight logged')})}
function noteModal(){openModal('New gym note',`<label>Title<input id="mTitle" placeholder="e.g. Squat cues" required></label><label>Tag<input id="mTag" placeholder="FORM / RECOVERY / IDEA"></label><label>Note<textarea id="mBody" rows="7" required></textarea></label>`,()=>{state.notes.push({id:uid(),title:$('#mTitle').value,tag:$('#mTag').value||'NOTE',body:$('#mBody').value,date:todayKey()});save();toast('Note saved')})}
function prModal(){openModal('Add personal record',`<label>Exercise<input id="mExercise" required placeholder="Bench Press"></label><label>Weight (kg)<input id="mPrWeight" type="number" step="0.5" required></label><label>Reps<input id="mPrReps" type="number" value="1" required></label><label>Date<input id="mPrDate" type="date" value="${todayKey()}" required></label>`,()=>{state.prs.push({id:uid(),exercise:$('#mExercise').value,weight:+$('#mPrWeight').value,reps:+$('#mPrReps').value,date:$('#mPrDate').value});save();toast('PR added')})}
function mealModal(){openModal('Log food',`<label>Food / meal<input id="mFood" required placeholder="Rice + chicken + dal"></label><label>Calories<input id="mCal" type="number" required></label><label>Protein (g)<input id="mProtein" type="number" value="0"></label><label>Carbs (g)<input id="mCarbs" type="number" value="0"></label><label>Fat (g)<input id="mFat" type="number" value="0"></label>`,()=>{const k=todayKey();state.meals[k]=state.meals[k]||[];state.meals[k].push({id:uid(),name:$('#mFood').value,cal:+$('#mCal').value,protein:+$('#mProtein').value,carbs:+$('#mCarbs').value,fat:+$('#mFat').value});save();toast('Meal logged')})}
function measureModal(){openModal('Body measurements',`<label>Chest (cm)<input id="mChest" type="number" step="0.1"></label><label>Waist (cm)<input id="mWaist" type="number" step="0.1"></label><label>Arms (cm)<input id="mArms" type="number" step="0.1"></label><label>Thigh (cm)<input id="mThigh" type="number" step="0.1"></label>`,()=>{state.measurements.push({id:uid(),date:todayKey(),chest:+$('#mChest').value||null,waist:+$('#mWaist').value||null,arms:+$('#mArms').value||null,thigh:+$('#mThigh').value||null});save();toast('Measurements saved')})}
function clientModal(){openModal('Add client',`<label>Name<input id="mClientName" required></label><label>Goal<input id="mClientGoal" placeholder="Lean bulk / Fat loss" required></label><label>Weight (kg)<input id="mClientWeight" type="number" step="0.1" required></label><label>Check-in<select id="mClientCheck"><option>Active</option><option>Due</option></select></label>`,()=>{state.clients.push({id:uid(),name:$('#mClientName').value,goal:$('#mClientGoal').value,weight:+$('#mClientWeight').value,checkin:$('#mClientCheck').value});save();toast('Client added')})}
function recoveryModal(){openModal('Update recovery',`<label>Sleep (hours)<input id="mSleep" type="number" step="0.5" value="${state.recovery.sleep}"></label><label>Water today (L)<input id="mWater" type="number" step="0.1" value="${state.recovery.water}"></label>`,()=>{state.recovery.sleep=+$('#mSleep').value;state.recovery.water=+$('#mWater').value;save();toast('Recovery updated')})}
// navigation
$$('.nav-item').forEach(b=>b.onclick=()=>navTo(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>navTo(b.dataset.jump));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#profileQuickBtn').onclick=()=>navTo('settings');
// modal
$('#modalForm').addEventListener('submit',e=>{e.preventDefault();if(modalHandler)modalHandler();$('#modal').close()});
$('#quickWeightBtn').onclick=$('#addWeightBtn').onclick=weightModal;$('#quickPrBtn').onclick=$('#addPrBtn').onclick=prModal;$('#quickNoteBtn').onclick=$('#addNoteBtn').onclick=noteModal;$('#addMealBtn').onclick=mealModal;$('#addMeasureBtn').onclick=measureModal;$('#addClientBtn').onclick=clientModal;$('#recoveryEditBtn').onclick=recoveryModal;
document.addEventListener('click',e=>{const t=e.target;if(t.dataset.wd!==undefined){selectedWorkout=+t.dataset.wd;renderWorkout();renderDashboard()}if(t.dataset.setDone){const ei=+t.dataset.ei,si=+t.dataset.si,key=workoutKey(selectedWorkout,ei),ex=workoutPlan[selectedWorkout].ex[ei];state.setLogs[key]=state.setLogs[key]||Array.from({length:ex[1]},()=>({kg:'',reps:'',done:false}));state.setLogs[key][si].done=!state.setLogs[key][si].done;save()}if(t.dataset.delMeal){state.meals[todayKey()]=(state.meals[todayKey()]||[]).filter(x=>x.id!==t.dataset.delMeal);save()}if(t.dataset.delWeight){state.weights=state.weights.filter(x=>x.id!==t.dataset.delWeight);save()}if(t.dataset.delNote){state.notes=state.notes.filter(x=>x.id!==t.dataset.delNote);save()}if(t.dataset.rest){restDefault=restSeconds=+t.dataset.rest;$$('[data-rest]').forEach(x=>x.classList.toggle('active',x===t));renderRest()}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.setField){const ei=+t.dataset.ei,si=+t.dataset.si,key=workoutKey(selectedWorkout,ei),ex=workoutPlan[selectedWorkout].ex[ei];state.setLogs[key]=state.setLogs[key]||Array.from({length:ex[1]},()=>({kg:'',reps:'',done:false}));state.setLogs[key][si][t.dataset.setField]=t.value;localStorage.setItem(STORE,JSON.stringify(state));}})
$('#finishWorkoutBtn').onclick=()=>{if(!state.workouts.some(w=>w.date===todayKey()&&w.day===selectedWorkout))state.workouts.push({id:uid(),date:todayKey(),day:selectedWorkout,name:workoutPlan[selectedWorkout].name});save();toast('Workout completed 🔥')}
$('#clearMealsBtn').onclick=()=>{if(confirm('Clear today’s food log?')){state.meals[todayKey()]=[];save()}}
$('#profileForm').onsubmit=e=>{e.preventDefault();Object.assign(state.profile,{name:$('#profileName').value,height:+$('#profileHeight').value,target:+$('#profileTarget').value,calories:+$('#profileCalories').value,protein:+$('#profileProtein').value,carbs:+$('#profileCarbs').value,fat:+$('#profileFat').value});const w=+$('#profileWeight').value;if(w!==latestWeight())state.weights.push({id:uid(),date:todayKey(),value:w});state.profile.weight=w;save();toast('Profile saved')}
$('#planBuilderForm').onsubmit=e=>{e.preventDefault();if(!$('#planClient').value)return toast('Add a client first');state.plans.push({id:uid(),clientId:$('#planClient').value,name:$('#planName').value,text:$('#planText').value,date:todayKey()});save();e.target.reset();toast('Plan assigned')}
$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='gymforge-backup-'+todayKey()+'.json';a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{try{state={...clone(defaults),...JSON.parse(await e.target.files[0].text())};save();toast('Backup imported')}catch{toast('Invalid backup file')}};
$('#resetBtn').onclick=()=>{if(confirm('Reset all local GymForge data?')){state=clone(defaults);save();toast('Data reset')}};
// session timer
function renderSession(){let m=Math.floor(sessionSeconds/60),s=sessionSeconds%60;$('#sessionTimer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
$('#sessionStartBtn').onclick=()=>{if(sessionInt){clearInterval(sessionInt);sessionInt=null;$('#sessionStartBtn').textContent='Start'}else{sessionInt=setInterval(()=>{sessionSeconds++;renderSession()},1000);$('#sessionStartBtn').textContent='Pause'}};$('#sessionResetBtn').onclick=()=>{clearInterval(sessionInt);sessionInt=null;sessionSeconds=0;renderSession();$('#sessionStartBtn').textContent='Start'};
// rest timer
function renderRest(){let m=Math.floor(restSeconds/60),s=restSeconds%60;$('#restDisplay').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
$('#restTimerBtn').onclick=()=>$('#restDialog').showModal();$('#restCloseBtn').onclick=()=>$('#restDialog').close();$('#restStartBtn').onclick=()=>{clearInterval(restInt);restInt=setInterval(()=>{restSeconds--;renderRest();if(restSeconds<=0){clearInterval(restInt);restInt=null;restSeconds=restDefault;toast('Rest over — next set!');setTimeout(renderRest,1200)}},1000)};$('#restResetBtn').onclick=()=>{clearInterval(restInt);restInt=null;restSeconds=restDefault;renderRest()};
// install pwa
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').style.display='inline-block'});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else toast('Use browser → Add to Home screen')};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
// Firebase adapter
let fb=null,cloudTimer=null;
async function initFirebase(){const cfg=window.GYMFORGE_FIREBASE_CONFIG;if(!cfg||!cfg.apiKey||String(cfg.apiKey).includes('PASTE_'))return;try{const appmod=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js');const authmod=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js');const fsmod=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js');const app=appmod.initializeApp(cfg),auth=authmod.getAuth(app),db=fsmod.getFirestore(app);fb={auth,db,authmod,fsmod};authmod.onAuthStateChanged(auth,async user=>{if(user){$('#syncDot').classList.add('online');$('#syncText').textContent='Cloud sync';await cloudLoad()}else{$('#syncDot').classList.remove('online');$('#syncText').textContent='Local mode'}})}catch(err){console.warn('Firebase init failed',err)}}
async function cloudLoad(){if(!fb?.auth.currentUser)return;try{const ref=fb.fsmod.doc(fb.db,'users',fb.auth.currentUser.uid);const snap=await fb.fsmod.getDoc(ref);if(snap.exists()){state={...clone(defaults),...snap.data().state};localStorage.setItem(STORE,JSON.stringify(state));renderAll()}else await cloudSave()}catch(e){console.warn(e)}}
async function cloudSave(){if(!fb?.auth.currentUser)return;try{await fb.fsmod.setDoc(fb.fsmod.doc(fb.db,'users',fb.auth.currentUser.uid),{state,updatedAt:Date.now()},{merge:true})}catch(e){console.warn(e)}}
function cloudSaveDebounced(){clearTimeout(cloudTimer);cloudTimer=setTimeout(cloudSave,700)}
$('#signupBtn').onclick=async()=>{if(!fb)return toast('Add Firebase config first');try{await fb.authmod.createUserWithEmailAndPassword(fb.auth,$('#authEmail').value,$('#authPassword').value);toast('Account created')}catch(e){toast(e.message.replace('Firebase: ','').slice(0,80))}};
$('#loginBtn').onclick=async()=>{if(!fb)return toast('Add Firebase config first');try{await fb.authmod.signInWithEmailAndPassword(fb.auth,$('#authEmail').value,$('#authPassword').value);toast('Logged in')}catch(e){toast(e.message.replace('Firebase: ','').slice(0,80))}};
$('#logoutBtn').onclick=async()=>{if(fb)await fb.authmod.signOut(fb.auth);toast('Logged out')};
window.addEventListener('resize',()=>{renderCharts();drawChart($('#weightMiniChart'),state.weights.slice(-8))});
renderAll();renderSession();renderRest();initFirebase();
